name: CI
on:
  pull_request:
    branches:
      - develop
    types: [ opened, synchronize, closed ]
jobs:
  ci:
    if: ${{ (github.event.pull_request.state == 'open' || github.event.pull_request.merged) || (github.event_name == 'pull_request' && !startsWith(github.event.pull_request.head.ref, 'release-please--')) }}
    name: CI
    runs-on: ubuntu-latest
    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      # Setup .NET
      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 9.0.x

      # Setup cache for NuGet dependencies
      - name: Setup .NET NuGet dependency cache
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('src/Calculator/Calculator.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget
    
      # Restore dependencies
      - name: Restore
        run: dotnet restore

      # Build application code
      - name: Build
        run: dotnet build --configuration Release --no-restore

      # Test application code
      - name: Test
        run: dotnet test --configuration Release --no-build --verbosity normal --logger "trx;LogFilename=test-results.trx" --results-directory="./TestResults"

      # Upload test results
      - name: Publish test results
        uses: actions/upload-artifact@v4.3.1
        if: success() || failure()
        with:
          name: test-results
          path: ./TestResults